name: fetch_client
description: Fetch based client for http package, enables streamed requests on web.
version: 1.0.0-dev.1
homepage: https://github.com/Zekfad/fetch_api
repository: https://github.com/Zekfad/fetch_api
issue_tracker: https://github.com/Zekfad/fetch_api/issues
# documentation: https://pub.dev/documentation/fetch_api/latest/

platforms:
  web:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  fetch_api: ^1.0.0-dev.1
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  zekfad_lints: ^1.2.0
